### ISSUE TITLE
@inherit is not used in several fields

### ISSUE THREAD

**Issue by logopk** [codescape/jira-multiple-subtasks#92]
Hi,

we are currently evaluation the app on Jira 9.4.

When adding a subtask likte this

```
- @inherit - My Test 4
  priority:@inherit
  assignee: Bob
  description:@inherit
  dueDate: @now+30d
  customfield_10625:@inherit
  customfield_10558:@inherit
  customfield_10537:@inherit
```
we get info messages on priority and customfield_10625 (invalid priority or option). while priority is filled with "high" (probably first entry), customfield_10625 is not filled at all.
description, customfield_10558 and customfield_10537 are filled with the value "@inherit"

I read that customfields are no supported yet (#79) , but description and priority?

Would it be possible to implement customfields soonish?

Thanks and best regards

Peter

**Comment by codescape** [comment]
Hey Peter,
here are my answers:

* **priority** by default inherits from the parent, see https://jira-multiple-subtasks.codescape.de/syntax#priority 
I can also provide a syntax like `priority: @inherit` but removing this line has the same effect because priority will always be inherited if not provided. 
* **description** does not support `@inherit` until now, see https://jira-multiple-subtasks.codescape.de/syntax#description
 I will create an issue for that.
* **custom fields** do not support `@inherit` until now. This is already planned in #79 
* **reporter** does not support `@inherit` until now. I will create an issue for that.
* **estmate** does not support `@inherit` until now. I will create an issue for that.

The full support of the syntax can be found in the documentation:
https://jira-multiple-subtasks.codescape.de/syntax

**Comment by codescape** [comment]
I am closing this issue because everything is adressed in separate issues now.

**Comment by logopk** [comment]
@codescape : Thank you for you reply. If I may vote for the order of completion?!
#79
#97
Priority default from parent is fine with me (just overread it in the really good documentation)

**Comment by codescape** [comment]
Hey @logopk, just wanted to let you know that version 23.05.1 is released and contains all those changes.
